### PR TITLE
Feature/serialization siblings

### PR DESCRIPTION
**Pull request by hexthedev**
* Made serialization nodes have keys so that they can be siblings
* Changed apparatus serialization to only have paths and metadata
* Changed apparatus loading to work completely based on metadata
* Updated apparatus jsons
* Wrote a release version of the apparatus Container
* Added Skybox capabilities to the Container
* Container entry point renamed to "AtomataScene"

### CODE REVIEW

**Comment by Ysabz** [comment]
I have a few questions: 
1) they serialization node had key before right? how that helps in having siblings?
2) The identifier field does not exists on the json anymore. To get the identifier of the apparatus should we look at the identifier of the first element in the path ? 
3) is there any changes needed in the container or provider codes ?

**Comment by hexthedev** [comment]
Q1) The serialization node didn't have a key before. Now the `identifier` is used to give it a unique id in the path, and the `key` is used to actually pull the apparatus from the backend. This means you can have the same key. but different ids.

**Comment by hexthedev** [comment]
Q2) I removed all the extra info because I realized it can all be given via metadata. You're right, to get the apparatus info, you can just look at the metadata in the root (1st path). 

It's possible that in the future, that we need to attach specific info to the apparatus that dosen't belong in meta, but its not clear atm. Everything for now can be parsed from meta.

**Comment by hexthedev** [comment]
Q3) We will need to rebuild the container cause I changed some of the code that runs it. That should be my job to test though, so I won't merge until I do that.

**Pull request merged**
